[package]
name = "tim2-viewer"
version = "0.1.0"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"


[dependencies]
tim2 = { path = "../lib" }

iced = { version = "0.1", features = ['image'] }
iced_native = "0.2"

anyhow = "1.0"
glob = "0.3"
structopt = "0.3"